### ISSUE TITLE
网易云解锁只显示云解锁，用不了了

### ISSUE THREAD

**Issue by winkill2000** [sirpdboy/openwrt18.06#110]
![image](https://user-images.githubusercontent.com/52886124/109574492-fd184080-7b2a-11eb-820c-117a87313f68.png)

**Comment by winkill2000** [comment]
wifi6完整版0301版本

**Comment by danceking** [comment]
使用  Ipv6-S2021.03.09 版本，开启“解锁灰色歌曲” 后，网易云完全无法听歌了，一首都不行。
PS：macOS系统，证书已经完全信任。
