### ISSUE TITLE
能否加入vlan设置功能？

### ISSUE THREAD

**Issue by 1900forever** [sirpdboy/openwrt18.06#157]
RT，之前好像在一个N1的编译版中看到过这个功能，不知道x86的能不能也加上？

**Comment by qyxk** [comment]
不是全世界的openwrt都支持吗

**Comment by helleon** [comment]
> 不是全世界的openwrt都支持吗

是说没有vlan子菜单吧

**Comment by 1900forever** [comment]
> > 不是全世界的openwrt都支持吗
> 
> 是说没有vlan子菜单吧
对

**Comment by sirpdboy** [comment]
带VLAN的设置的。 百度一下。
