### ISSUE TITLE
每次重启一分钟左右内存爆满，然后卡死。

### ISSUE THREAD

**Issue by ywtk1979** [sirpdboy/openwrt18.06#161]
每次重启 在一分钟左右，IP v6 进行连接的时候，内存会迅速占满，进而卡死，无法进luci管理界面。初次配置时禁用IP v6，就不会出现该问题。

**Comment by ywtk1979** [comment]
最近两个版本都这样

**Comment by rikechen** [comment]
最近的版本都会无征兆死机现象

**Comment by sirpdboy** [comment]
设置原因，或者冲突。不支持IPV6的话，建议关闭。
