### ISSUE TITLE
关于Samba的local master browser问题

### ISSUE THREAD

**Issue by Dante-github** [sirpdboy/openwrt18.06#164]
最近软路由一直发热很厉害，看了下系统日志一直在循环报错，全都是关于local master browser的，这个是需要怎么配置呢，我把软路由上所有Samba都关了也不行。是需要去另一个设备上设置吗，可是我另一个设备是个电视盒子......

Fri Jul  2 08:43:31 2021 daemon.err nmbd[25827]: [2021/07/02 08:43:31.875164,  0] ../../source3/nmbd/nmbd_incomingdgrams.c:304(process_local_master_announce)
Fri Jul  2 08:43:31 2021 daemon.err nmbd[25827]:   process_local_master_announce: Server SHIELD at IP 192.168.10.36 is announcing itself as a local master browser for workgroup WORKGROUP and we think we are master. Forcing election.
Fri Jul  2 08:43:31 2021 daemon.err nmbd[25827]: [2021/07/02 08:43:31.875530,  0] ../../source3/nmbd/nmbd_become_lmb.c:150(unbecome_local_master_success)
Fri Jul  2 08:43:31 2021 daemon.err nmbd[25827]:   *****
Fri Jul  2 08:43:31 2021 daemon.err nmbd[25827]:
Fri Jul  2 08:43:31 2021 daemon.err nmbd[25827]:   Samba name server OPENWRT has stopped being a local master browser for workgroup WORKGROUP on subnet 192.168.10.251
Fri Jul  2 08:43:31 2021 daemon.err nmbd[25827]:
Fri Jul  2 08:43:31 2021 daemon.err nmbd[25827]:   *****
Fri Jul  2 08:43:49 2021 daemon.err nmbd[25827]: [2021/07/02 08:43:49.897074,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
Fri Jul  2 08:43:49 2021 daemon.err nmbd[25827]:   *****
Fri Jul  2 08:43:49 2021 daemon.err nmbd[25827]:
Fri Jul  2 08:43:49 2021 daemon.err nmbd[25827]:   Samba name server OPENWRT is now a local master browser for workgroup WORKGROUP on subnet 192.168.10.251
Fri Jul  2 08:43:49 2021 daemon.err nmbd[25827]:
Fri Jul  2 08:43:49 2021 daemon.err nmbd[25827]:   *****
Fri Jul  2 08:55:32 2021 daemon.err nmbd[25827]: [2021/07/02 08:55:32.579430,  0] ../../source3/nmbd/nmbd_incomingdgrams.c:304(process_local_master_announce)
Fri Jul  2 08:55:32 2021 daemon.err nmbd[25827]:   process_local_master_announce: Server SHIELD at IP 192.168.10.36 is announcing itself as a local master browser for workgroup WORKGROUP and we think we are master. Forcing election.
Fri Jul  2 08:55:32 2021 daemon.err nmbd[25827]: [2021/07/02 08:55:32.579865,  0] ../../source3/nmbd/nmbd_become_lmb.c:150(unbecome_local_master_success)
Fri Jul  2 08:55:32 2021 daemon.err nmbd[25827]:   *****
Fri Jul  2 08:55:32 2021 daemon.err nmbd[25827]:
Fri Jul  2 08:55:32 2021 daemon.err nmbd[25827]:   Samba name server OPENWRT has stopped being a local master browser for workgroup WORKGROUP on subnet 192.168.10.251
Fri Jul  2 08:55:32 2021 daemon.err nmbd[25827]:
Fri Jul  2 08:55:32 2021 daemon.err nmbd[25827]:   *****
Fri Jul  2 08:55:49 2021 daemon.err nmbd[25827]: [2021/07/02 08:55:49.599644,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
Fri Jul  2 08:55:49 2021 daemon.err nmbd[25827]:   *****
Fri Jul  2 08:55:49 2021 daemon.err nmbd[25827]:
Fri Jul  2 08:55:49 2021 daemon.err nmbd[25827]:   Samba name server OPENWRT is now a local master browser for workgroup WORKGROUP on subnet 192.168.10.251
Fri Jul  2 08:55:49 2021 daemon.err nmbd[25827]:
Fri Jul  2 08:55:49 2021 daemon.err nmbd[25827]:   *****

**Comment by sirpdboy** [comment]
共享冲突或者服务出错。建议恢复出厂重新调试。
