### ISSUE TITLE
7.05 版本可以挂载1.8T NTFS 分区 但为只读模式 ！

### ISSUE THREAD

**Issue by zydfq** [sirpdboy/openwrt18.06#166]
如题：
挂载路径为：/mnt/sdb1
用 chmod -R 777  /mnt/sdb1/

反馈信息：chmod: /mnt/sdb1: Read-only file system

6.18版以前版本均无此问题！请您留意此问题！

**Comment by zydfq** [comment]
暂退回6.18 版。谢谢您慷慨付出！期待无错版......

**Comment by zydfq** [comment]
此次更新，为全新更新，手动回复设置。不牵扯备份还原问题！

**Comment by zydfq** [comment]
koolddns
还是反馈  
远程解析 IP  “error”

**Comment by sirpdboy** [comment]
新版本已经解决此问题。
