### ISSUE TITLE
JD签到获取Cookies失败

### ISSUE THREAD

**Issue by Dante-github** [sirpdboy/openwrt18.06#168]
有一天Cookies提示失效了，扫码重新获取的时候发现，扫码后，Cookies无法正常带出来，二维码提示刷新。
脚本已点击了最下方的更新已是最新版，仍无法解决。

**Comment by bawanag** [comment]
同问，该问题已经持续了一个多月了

**Comment by showme2005** [comment]
> 同问，该问题已经持续了一个多月了

自己去github上面找JD签到COOKIE获取器

**Comment by sirpdboy** [comment]
新版本 应该是没问题的。
