### ISSUE TITLE
访问限制 无法开启

### ISSUE THREAD

**Issue by zydfq** [sirpdboy/openwrt18.06#173]
系统版本：OpenWrt Ipv6-S2021.07.24 by Sirpdboy 
访问限制 无法开启
选中总开关 
运行状态 : 没有运行

**Comment by sirpdboy** [comment]
要启用限制的机器才提示生效。

**Comment by zydfq** [comment]
确定是完整设置。确定多次测试均以“启用限制的机器”相关项。显示运行状态为没有运行才向您提交本问题。

**Comment by sirpdboy** [comment]
好的。 如果不行，暂时用 上网时间 控制和管控过滤 试试。

**Comment by sirpdboy** [comment]
下个版本将修复 这个问题，感谢提交问题。
