### ISSUE TITLE
老是异常掉线并且自动拨号。麻烦修复一下呀。j1900的机子

### ISSUE THREAD

**Issue by 710511985** [sirpdboy/openwrt18.06#194]
Tue Sep 14 20:00:00 2021 cron.err crond[12662]: USER root pid 15075 cmd sync && echo 3 > /proc/sys/vm/drop_caches
Tue Sep 14 20:00:00 2021 kern.info kernel: [1072780.320442] ash (15075): drop_caches: 3
Tue Sep 14 20:25:14 2021 kern.info kernel: [1074293.603865] igb 0000:01:00.0 eth0: igb: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Tue Sep 14 20:25:16 2021 kern.err kernel: [1074295.767500] igb 0000:01:00.0: exceed max 2 second
Tue Sep 14 20:25:16 2021 kern.info kernel: [1074295.772959] igb 0000:01:00.0 eth0: igb: eth0 NIC Link is Down
Tue Sep 14 20:25:17 2021 kern.info kernel: [1074296.887958] igb 0000:01:00.0 eth0: igb: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Tue Sep 14 20:25:17 2021 kern.info kernel: [1074296.893601] br-lan: port 1(eth0) entered blocking state
Tue Sep 14 20:25:17 2021 kern.info kernel: [1074296.898765] br-lan: port 1(eth0) entered forwarding state
Tue Sep 14 20:25:17 2021 daemon.notice netifd: Network device 'eth0' link is up
Tue Sep 14 20:25:26 2021 kern.info kernel: [1074305.779847] igb 0000:01:00.0 eth0: igb: eth0 NIC Link is Down
Tue Sep 14 20:25:26 2021 kern.info kernel: [1074305.785448] br-lan: port 1(eth0) entered disabled state
Tue Sep 14 20:25:26 2021 daemon.notice netifd: Network device 'eth0' link is down
Tue Sep 14 20:25:29 2021 kern.info kernel: [1074308.816282] igb 0000:01:00.0 eth0: igb: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
Tue Sep 14 20:25:29 2021 kern.info kernel: [1074308.821909] br-lan: port 1(eth0) entered blocking state
Tue Sep 14 20:25:29 2021 kern.info kernel: [1074308.827104] br-lan: port 1(eth0) entered forwarding state
Tue Sep 14 20:25:29 2021 daemon.notice netifd: Network device 'eth0' link is up
Tue Sep 14 21:50:14 2021 kern.info kernel: [1079394.484490] igb 0000:02:00.0 eth1: igb: eth1 NIC Link is Down
Tue Sep 14 21:50:14 2021 daemon.notice netifd: Network device 'eth1' link is down
Tue Sep 14 21:50:14 2021 daemon.notice netifd: Interface 'wan' has link connectivity loss
Tue Sep 14 21:50:14 2021 daemon.notice netifd: Interface 'wan6' has link connectivity loss
Tue Sep 14 21:50:14 2021 daemon.info pppd[25859]: Terminating on signal 15
Tue Sep 14 21:50:14 2021 daemon.info pppd[25859]: Connect time 706.9 minutes.
Tue Sep 14 21:50:14 2021 daemon.info pppd[25859]: Sent 703457796 bytes, received 613714988 bytes.
Tue Sep 14 21:50:14 2021 daemon.info avahi-daemon[4583]: Withdrawing address record for 10.16.74.129 on pppoe-wan.
Tue Sep 14 21:50:14 2021 daemon.info avahi-daemon[4583]: Leaving mDNS multicast group on interface pppoe-wan.IPv4 with address 10.16.74.129.
Tue Sep 14 21:50:14 2021 daemon.info avahi-daemon[4583]: Interface pppoe-wan.IPv4 no longer relevant for mDNS.
Tue Sep 14 21:50:14 2021 daemon.notice netifd: Network device 'pppoe-wan' link is down
Tue Sep 14 21:50:14 2021 daemon.notice netifd: Network alias 'pppoe-wan' link is down
Tue Sep 14 21:50:14 2021 daemon.notice netifd: Interface 'wan_6' has link connectivity loss
Tue Sep 14 21:50:14 2021 daemon.err odhcp6c[28534]: Failed to send RELEASE message to ff02::1:2 (Permission denied)
Tue Sep 14 21:50:14 2021 daemon.info avahi-daemon[4583]: Interface pppoe-wan.IPv6 no longer relevant for mDNS.
Tue Sep 14 21:50:14 2021 daemon.info avahi-daemon[4583]: Leaving mDNS multicast group on interface pppoe-wan.IPv6 with address 240e:33c:1:61f3:4463:ce25:4c20:33d.
Tue Sep 14 21:50:14 2021 daemon.info avahi-daemon[4583]: Withdrawing address record for 240e:33c:1:61f3:4463:ce25:4c20:33d on pppoe-wan.
Tue Sep 14 21:50:14 2021 daemon.notice netifd: wan_6 (28534): Command failed: Permission denied
Tue Sep 14 21:50:15 2021 daemon.err odhcp6c[28534]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
Tue Sep 14 21:50:15 2021 daemon.notice netifd: Interface 'wan_6' is now down
Tue Sep 14 21:50:15 2021 daemon.info avahi-daemon[4583]: Withdrawing address record for 240e:33d:18:1b0::1 on br-lan.
Tue Sep 14 21:50:15 2021 daemon.notice netifd: Interface 'wan_6' is disabled
Tue Sep 14 21:50:15 2021 daemon.notice netifd: Interface 'wan6' is now down
Tue Sep 14 21:50:16 2021 daemon.info netdata[9700]: Initializing file /var/cache/netdata/net_drops.pppoe_wan/main.db.
Tue Sep 14 21:50:16 2021 daemon.info netdata[9700]: Initializing file /var/cache/netdata/net_drops.pppoe_wan/inbound.db.
Tue Sep 14 21:50:16 2021 daemon.info netdata[9700]: Initializing file /var/cache/netdata/net_drops.pppoe_wan/outbound.db.
Tue Sep 14 21:50:18 2021 daemon.notice netifd: Network device 'eth1' link is up
Tue Sep 14 21:50:18 2021 daemon.notice netifd: Interface 'wan' has link connectivity
Tue Sep 14 21:50:18 2021 daemon.notice netifd: Interface 'wan6' has link connectivity
Tue Sep 14 21:50:18 2021 daemon.notice netifd: Interface 'wan6' is setting up now
Tue Sep 14 21:50:18 2021 kern.info kernel: [1079398.116993] igb 0000:02:00.0 eth1: igb: eth1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
Tue Sep 14 21:50:19 2021 daemon.notice netifd: Interface 'wan' is now down
Tue Sep 14 21:50:19 2021 daemon.notice netifd: Interface 'wan' is setting up now
Tue Sep 14 21:50:19 2021 daemon.err insmod: module is already loaded - slhc
Tue Sep 14 21:50:19 2021 daemon.err insmod: module is already loaded - ppp_generic
Tue Sep 14 21:50:19 2021 daemon.err insmod: module is already loaded - pppox
Tue Sep 14 21:50:19 2021 daemon.err insmod: module is already loaded - pppoe
Tue Sep 14 21:50:20 2021 daemon.info pppd[2066]: Plugin rp-pppoe.so loaded.
Tue Sep 14 21:50:20 2021 daemon.info pppd[2066]: RP-PPPoE plugin version 3.8p compiled against pppd 2.4.8
Tue Sep 14 21:50:20 2021 daemon.notice pppd[2066]: pppd 2.4.8 started by root, uid 0
Tue Sep 14 21:50:20 2021 daemon.info avahi-daemon[4583]: Interface ztks5z7a7n.IPv6 no longer relevant for mDNS.
Tue Sep 14 21:50:20 2021 daemon.info avahi-daemon[4583]: Leaving mDNS multicast group on interface ztks5z7a7n.IPv6 with address fe80::80f1:73ff:fec6:dddc.
Tue Sep 14 21:50:20 2021 daemon.info avahi-daemon[4583]: Withdrawing address record for fe80::80f1:73ff:fec6:dddc on ztks5z7a7n.
Tue Sep 14 21:50:22 2021 daemon.err zerotier-one[2373]: sendto: Network unreachable
Tue Sep 14 21:50:23 2021 daemon.info avahi-daemon[4583]: Joining mDNS multicast group on interface ztks5z7a7n.IPv6 with address fe80::d4a0:96ff:fe79:287a.
Tue Sep 14 21:50:23 2021 daemon.info avahi-daemon[4583]: New relevant interface ztks5z7a7n.IPv6 for mDNS.
Tue Sep 14 21:50:23 2021 daemon.info avahi-daemon[4583]: Registering new address record for fe80::d4a0:96ff:fe79:287a on ztks5z7a7n.*.
Tue Sep 14 21:50:24 2021 daemon.info netdata[9700]: RRDSET: chart name 'net.ztks5z7a7n' on host 'OpenWrt' already exists.
Tue Sep 14 21:50:24 2021 daemon.info netdata[9700]: RRDSET: chart name 'net_operstate.ztks5z7a7n' on host 'OpenWrt' already exists.
Tue Sep 14 21:50:24 2021 daemon.info netdata[9700]: RRDSET: chart name 'net_carrier.ztks5z7a7n' on host 'OpenWrt' already exists.
Tue Sep 14 21:50:24 2021 daemon.info netdata[9700]: RRDSET: chart name 'net_mtu.ztks5z7a7n' on host 'OpenWrt' already exists.
Tue Sep 14 21:50:24 2021 daemon.info netdata[9700]: RRDSET: chart name 'net_packets.ztks5z7a7n' on host 'OpenWrt' already exists.
Tue Sep 14 21:50:30 2021 daemon.info pppd[2066]: PPP session is 15645
Tue Sep 14 21:50:30 2021 daemon.warn pppd[2066]: Connected to 00:25:12:52:28:37 via interface eth1
Tue Sep 14 21:50:30 2021 kern.info kernel: [1079409.858657] pppoe-wan: renamed from ppp0
Tue Sep 14 21:50:30 2021 daemon.info pppd[2066]: Renamed interface ppp0 to pppoe-wan
Tue Sep 14 21:50:30 2021 daemon.info pppd[2066]: Using interface pppoe-wan
Tue Sep 14 21:50:30 2021 daemon.notice pppd[2066]: Connect: pppoe-wan <--> eth1
Tue Sep 14 21:50:32 2021 daemon.err netdata[9700]: Cannot refresh interface pppoe-wan carrier state by reading '/sys/class/net/pppoe-wan/carrier'. Stop updating it.
Tue Sep 14 21:50:32 2021 daemon.info netdata[9700]: RRDSET: chart name 'net.pppoe_wan' on host 'OpenWrt' already exists.
Tue Sep 14 21:50:32 2021 daemon.info netdata[9700]: RRDSET: chart name 'net_operstate.pppoe_wan' on host 'OpenWrt' already exists.
Tue Sep 14 21:50:32 2021 daemon.info netdata[9700]: RRDSET: chart name 'net_mtu.pppoe_wan' on host 'OpenWrt' already exists.
Tue Sep 14 21:50:35 2021 daemon.info pppd[2066]: syncppp not active
Tue Sep 14 21:50:35 2021 daemon.info pppd[2066]: Remote message: Authentication success,Welcome!
Tue Sep 14 21:50:35 2021 daemon.notice pppd[2066]: PAP authentication succeeded
Tue Sep 14 21:50:35 2021 daemon.notice pppd[2066]: peer from calling number 00:25:12:52:28:37 authorized
Tue Sep 14 21:50:35 2021 daemon.notice pppd[2066]: local  LL address fe80::09d2:a716:0715:92d4
Tue Sep 14 21:50:35 2021 daemon.notice pppd[2066]: remote LL address fe80::0225:12ff:fe52:2837
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: Joining mDNS multicast group on interface pppoe-wan.IPv6 with address fe80::9d2:a716:715:92d4.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: New relevant interface pppoe-wan.IPv6 for mDNS.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: Registering new address record for fe80::9d2:a716:715:92d4 on pppoe-wan.*.
Tue Sep 14 21:50:35 2021 daemon.notice pppd[2066]: local  IP address 10.16.99.176
Tue Sep 14 21:50:35 2021 daemon.notice pppd[2066]: remote IP address 10.16.0.1
Tue Sep 14 21:50:35 2021 daemon.notice pppd[2066]: primary   DNS address 222.85.85.85
Tue Sep 14 21:50:35 2021 daemon.notice pppd[2066]: secondary DNS address 222.88.88.88
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: Joining mDNS multicast group on interface pppoe-wan.IPv4 with address 10.16.99.176.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: New relevant interface pppoe-wan.IPv4 for mDNS.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: Registering new address record for 10.16.99.176 on pppoe-wan.IPv4.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: Withdrawing address record for 10.16.99.176 on pppoe-wan.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: Leaving mDNS multicast group on interface pppoe-wan.IPv4 with address 10.16.99.176.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: Interface pppoe-wan.IPv4 no longer relevant for mDNS.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: Joining mDNS multicast group on interface pppoe-wan.IPv4 with address 10.16.99.176.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: New relevant interface pppoe-wan.IPv4 for mDNS.
Tue Sep 14 21:50:35 2021 daemon.info avahi-daemon[4583]: Registering new address record for 10.16.99.176 on pppoe-wan.IPv4.
Tue Sep 14 21:50:35 2021 daemon.notice netifd: Network device 'pppoe-wan' link is up
Tue Sep 14 21:50:35 2021 daemon.notice netifd: Interface 'wan' is now up
Tue Sep 14 21:50:35 2021 user.notice firewall: Reloading firewall due to ifup of wan (pppoe-wan)
Tue Sep 14 21:50:36 2021 daemon.info netdata[9700]: RRDSET: chart name 'net_packets.pppoe_wan' on host 'OpenWrt' already exists.
Tue Sep 14 21:50:36 2021 daemon.info avahi-daemon[4583]: Interface ztks5z7a7n.IPv6 no longer relevant for mDNS.
Tue Sep 14 21:50:36 2021 daemon.info avahi-daemon[4583]: Leaving mDNS multicast group on interface ztks5z7a7n.IPv6 with address fe80::d4a0:96ff:fe79:287a.
Tue Sep 14 21:50:36 2021 daemon.info avahi-daemon[4583]: Withdrawing address record for fe80::d4a0:96ff:fe79:287a on ztks5z7a7n.
Tue Sep 14 21:50:38 2021 user.notice nlbwmon: Reloading nlbwmon due to ifup of wan (pppoe-wan)
Tue Sep 14 21:50:38 2021 user.notice wrtbwmon: Restart for ifup of wan (pppoe-wan)
Tue Sep 14 21:50:38 2021 user.notice firewall: Reloading firewall due to ifupdate of wan (pppoe-wan)
Tue Sep 14 21:50:38 2021 daemon.info avahi-daemon[4583]: Joining mDNS multicast group on interface ztks5z7a7n.IPv6 with address fe80::4085:3bff:feaa:fb15.
Tue Sep 14 21:50:38 2021 daemon.info avahi-daemon[4583]: New relevant interface ztks5z7a7n.IPv6 for mDNS.
Tue Sep 14 21:50:38 2021 daemon.info avahi-daemon[4583]: Registering new address record for fe80::4085:3bff:feaa:fb15 on ztks5z7a7n.*.
Tue Sep 14 21:50:39 2021 user.notice wrtbwmon: Restart for ifupdate of wan (pppoe-wan)
Tue Sep 14 21:51:24 2021 daemon.info netdata[9700]: RRDSET: chart name 'net_drops.pppoe_wan' on host 'OpenWrt' already exists.
Tue Sep 14 21:51:35 2021 daemon.notice netifd: Network alias 'pppoe-wan' link is up
Tue Sep 14 21:51:35 2021 daemon.notice netifd: Interface 'wan_6' is enabled
Tue Sep 14 21:51:35 2021 daemon.notice netifd: Interface 'wan_6' has link connectivity
Tue Sep 14 21:51:35 2021 daemon.notice netifd: Interface 'wan_6' is setting up now
Tue Sep 14 21:51:38 2021 daemon.info avahi-daemon[4583]: Leaving mDNS multicast group on interface pppoe-wan.IPv6 with address fe80::9d2:a716:715:92d4.
Tue Sep 14 21:51:38 2021 daemon.info avahi-daemon[4583]: Joining mDNS multicast group on interface pppoe-wan.IPv6 with address 240e:33c:1:78e7:9d2:a716:715:92d4.
Tue Sep 14 21:51:38 2021 daemon.info avahi-daemon[4583]: Registering new address record for 240e:33c:1:78e7:9d2:a716:715:92d4 on pppoe-wan.*.
Tue Sep 14 21:51:38 2021 daemon.info avahi-daemon[4583]: Withdrawing address record for fe80::9d2:a716:715:92d4 on pppoe-wan.
Tue Sep 14 21:51:38 2021 daemon.info avahi-daemon[4583]: Registering new address record for 240e:33d:19:2b00::1 on br-lan.*.
Tue Sep 14 21:51:38 2021 daemon.notice netifd: Interface 'wan_6' is now up
Tue Sep 14 21:51:39 2021 user.notice firewall: Reloading firewall due to ifup of wan_6 (pppoe-wan)
Tue Sep 14 21:51:39 2021 user.notice nlbwmon: Reloading nlbwmon due to ifup of wan_6 (pppoe-wan)
Tue Sep 14 21:51:39 2021 user.notice wrtbwmon: Restart for ifup of wan_6 (pppoe-wan)

**Comment by sirpdboy** [comment]
这是驱动 关系。需要配套的驱动
