### ISSUE TITLE
如何编译使用您固件中 宽带监控里usage的页面。

### ISSUE THREAD

**Issue by jk2008chd** [sirpdboy/openwrt18.06#195]
您好，sirpdboy。 大佬，我非常喜欢您的固件，也在用您的插件库编译，但是有美中不足的地方我尝试学习了好多天不得其解。遂来叨扰。
您固件中宽带监控usage项我页面非常好看。我非常想在自己编译的固件中加入。苦思不得解，在/usr/lib/lua/luci/view 中找到了该web页面，但是不知如何替换与使用。 真心求教 .

**Comment by sirpdboy** [comment]
删除 源码中的 ，用仓库中的编译就行了。
