### ISSUE TITLE
重刷3天之后又无法保存配置.无法更换节点.重启之后自动恢复出厂设置.

### ISSUE THREAD

**Issue by ab2347568** [sirpdboy/openwrt18.06#235]
重刷3天之后又无法保存配置.无法更换节点.重启之后自动恢复出厂设置.
![image](https://user-images.githubusercontent.com/72936631/141974527-72f1ab98-f42f-48ba-98d6-3d1d05b3efed.png)
这个地方变成0....

我11月1号和11月10号都有这个问题.大全版

**Comment by sirpdboy** [comment]
和固件无关。是你空间用完了。。自己扩展 一下呀
