### ISSUE TITLE
无法使用备份/升级功能

### ISSUE THREAD

**Issue by Nighting0518** [sirpdboy/openwrt18.06#241]
OpenWrt Ipv6-S2021.10.01 by Sirpdboy / LuCI Master (git-21.238.35254-83494a9)升级11.10版本 从web上的备份/升级功能上传固件包后没有反应 保留配置勾不勾选都一样

**Comment by sirpdboy** [comment]
用DD升级。

**Comment by Nighting0518** [comment]
> 用DD升级。

好的 感谢大佬~
