### ISSUE TITLE
集成包内有隐藏应用偷跑科学上网流量

### ISSUE THREAD

**Issue by moudong168** [sirpdboy/openwrt18.06#249]
应用本集成包个月有余,今天突然不能科学上网,经查,本OPENWRT在近一个月内,长时间持续跑科学上网流量,导致VPS流量超限制,被VPS断了,看来这个集成包内的不明隐藏应用之猖狂,当前还没查出具体是什么偷流量,请使用的朋友注意.

**Comment by Alien3389** [comment]
我也发现了，之前都没有，这两天才开始的，一开代理，几百连接，不知道是什么东西在偷跑。
![QQ截图20211204221658](https://user-images.githubusercontent.com/9362876/144712806-420a825a-328b-429b-831e-ac7744274d44.png)

**Comment by Alien3389** [comment]
我也发现了，之前都没有，这两天才开始的，一开代理，几百连接，不知道是什么东西在偷跑。
![QQ截图20211204221658](https://user-images.githubusercontent.com/9362876/144712806-420a825a-328b-429b-831e-ac7744274d44.png)

**Comment by Alien3389** [comment]
![QQ截图20211204223028](https://user-images.githubusercontent.com/9362876/144713235-f1ff8437-22cb-4fa7-9eff-dea7fe94682d.png)
关掉插件也有在偷跑，这是没那么大

**Comment by sirpdboy** [comment]
这个就是软路由 LAN口 的地址。如果哪个插件偷跑流量， 你们查一下，发日志过来。找各种插件开发者。不要没依据就乱说。
